cache:
  yarn: true
  directories:
    - node_modules
language: node_js
branches:
  only:
  - master
before_install:
  - npm install -g --no-progress yarn@v0.22.0
install:
  - yarn install --no-progress
script:
  - yarn test -- --coverage

after_success:
  - yarn prepublish
